{{ config(materialized='table') }}
 
SELECT * FROM "VWE"."PUBLIC"."ORDER_NEW" INNER JOIN "VWE"."PUBLIC"."ORDER_TABLE" ON "VWE"."PUBLIC"."ORDER_NEW".CUSTOMER_NAME = "VWE"."PUBLIC"."ORDER_TABLE".CUSTOMER_NAME WHERE "VWE"."PUBLIC"."ORDER_TABLE".CUSTOMER_NAME = 'Claire Gute';
