{{ config(materialized='table') }}
 
SELECT COUNTRY,STATES,CITY,REGION,ORDER_ID FROM "VWE"."PUBLIC"."ORDER_NEW" c INNER JOIN "VWE"."PUBLIC"."ORDER_TABLE" ON "VWE"."PUBLIC"."ORDER_NEW".ORDER_ID = "VWE"."PUBLIC"."ORDER_TABLE".ORDER_ID WHERE "VWE"."PUBLIC"."ORDER_TABLE"."CUSTOMER_NAME" = 'Claire Gute'